version: "3.9"  # optional since v1.27.0

services:
  db:
    build:
      context: .
      dockerfile: ./gnaf_dockerfile
    restart: "no"
    container_name: gnaf_pg_service
    hostname: gnaf_pg_db
    image: gnaf_postgis:v1
    shm_size: 1gb
    user: postgres
    group_add:
      - "1000"                          # On Linux, change this to the group on ./data & ./scripts folders to avoid permissions issues with bind mounts, also host folders should have write/execute permission  (774, 754) for the group, middle number should be either 7 or 5!!   OR if host folder has 777, then no need for group_add...
    environment:
      POSTGRES_DB: geo                 # used in entrypoint script
      POSTGRES_USER: postgres              # used in entrypoint script
      POSTGRES_PASSWORD: geogeo!
      PGDATA: /var/lib/postgresql/data
      GNAF_SCHEMA: gnaf                    # used in entrypoint script
      USER_SCRIPTS: /scripts              # used in entrypoint script
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./entrypoint_scripts/90_gnaf_db_setup.sh
        target: /docker-entrypoint-initdb.d/90_gnaf_db_setup.sh
      - type: bind
        source: ./data                           # Extract GNAF data to this folder
        target: /gnaf_data
      - type: bind
        source: ./scripts
        target: /scripts
    ports:
      - "5432:5432"
volumes:
  db-data:
      name: "geo_db_volume"
